import type { Metadata } from "next";
import { Lekton } from "next/font/google";
import "./globals.css";

const lekton = Lekton({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "GranaControl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lekton.className} bg-background `}>{children}</body>
    </html>
  );
}
